sudo: required

services:
    - docker
before_install:
    - docker build -t mabdalla123/docker-react -f Dockerfile.dev .
    
script:
    - docker run mabdalla123/docker-react npm run test -- --coverage